In [1]:
import torch
import math
from rotation_utils import get_orthogonal_matrix

/usr/local/lib/python3.10/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
h = get_orthogonal_matrix(4096, 'hadamard', device='cuda')

In [3]:
q = get_orthogonal_matrix(4096, 'random', device='cuda')

In [ ]:
def compute_incoherence(x):
    norm_fro = torch.norm(x, p='fro')
    
    rhs = norm_fro / math.sqrt(x.size(0) * x.size(1))
    
    L, V = torch.linalg.eig(x)
    
    

In [21]:
norm_fro = torch.norm(q, p='fro')

In [22]:
norm_fro

tensor(64., device='cuda:0', dtype=torch.float64)

In [23]:
norm_fro = torch.norm(h, p='fro')

In [24]:
norm_fro

tensor(64., device='cuda:0', dtype=torch.float64)

In [15]:
with torch.no_grad():
    L, V = torch.linalg.eig(q)

In [16]:
L

tensor([ 0.7078+0.7064j,  0.7078-0.7064j,  0.7094+0.7048j,  ...,
        -0.9999-0.0135j, -0.9922+0.1250j, -0.9922-0.1250j], device='cuda:0',
       dtype=torch.complex128)

In [17]:
L.real ** 2 + L.imag ** 2

tensor([1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000], device='cuda:0',
       dtype=torch.float64)

In [5]:
L.size()

torch.Size([4096])

In [6]:
V.size()

torch.Size([4096, 4096])

In [7]:
dL = torch.diag(L)

In [8]:
Vinv = torch.linalg.inv(V)

In [9]:
VdL = torch.matmul(V, dL)

In [10]:
VdLVinv = torch.matmul(VdL, Vinv)

In [12]:
h - VdLVinv

tensor([[ 4.1633e-15+4.6478e-16j, -9.8532e-16+4.8217e-16j,
         -1.4433e-15-1.6143e-15j,  ...,
         -6.9389e-16+5.5129e-16j, -1.1900e-15+1.3475e-15j,
          8.2746e-16+4.6073e-16j],
        [-9.9573e-16+1.4617e-15j,  1.5907e-15+1.1424e-15j,
          9.0553e-16+5.3963e-16j,  ...,
         -8.0491e-16+1.9523e-15j, -1.8006e-15+2.0766e-18j,
         -3.1919e-16+1.4188e-15j],
        [ 9.5757e-16-2.5200e-15j, -5.7593e-16-1.9049e-16j,
         -1.8839e-15+9.9399e-16j,  ...,
         -1.5613e-17-1.5832e-15j,  1.0859e-15+2.2876e-17j,
          3.3463e-15+3.7337e-15j],
        ...,
        [ 7.6848e-16-9.6640e-16j,  8.9512e-16-4.8929e-17j,
         -4.9613e-16-5.3368e-16j,  ...,
          1.7174e-15-2.7426e-16j,  6.4011e-16-2.0772e-16j,
          3.0982e-15+4.6330e-16j],
        [ 5.8287e-16+2.4279e-16j, -2.2551e-15+1.8124e-15j,
         -9.0206e-17+3.7313e-16j,  ...,
         -2.1528e-15-3.0398e-16j,  7.9624e-16+7.9023e-16j,
         -9.9573e-16+8.5313e-16j],
        [ 1.6289e-15-6

In [18]:
with torch.no_grad():
    L = torch.linalg.eigvals(q)

In [19]:
L

tensor([ 0.6858+0.7278j,  0.6858-0.7278j,  0.6895+0.7243j,  ...,
        -0.9999-0.0135j, -0.9922+0.1250j, -0.9922-0.1250j], device='cuda:0',
       dtype=torch.complex128)